# Inspired by https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

default:
  image: python:3.10

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
  
.base_environment:
  before_script:
    - apt-get update -qy
    - apt-get install -y coinor-cbc git graphviz
    - pip install .

# Make the default stages explicit
stages:
  - linting
  - test
  - build
  - deploy

ruff:
  extends: .base_environment
  stage: linting
  script:
    - pip install ruff
    - ruff check --output-format=gitlab .
  allow_failure: false

pytest:
  extends: .base_environment
  stage: test
  script:
    # run tox using the settings defined in tox.ini
    - tox
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    paths:
      # the report is placed in this folder by default, can be changed by adding ':DEST' after 'html' where DEST is the target folder
      - htmlcov/

  allow_failure: false

pages:
  extends: .base_environment
  stage: build
  needs: ["pytest"]
  script:
    # pdoc is used to generate the documentation
    - pip install pdoc
    # generates the API documentation
    - pdoc src/mtress -o ./public/api/
    # generates the landing page
    - pdoc src/doc -o ./public/
    # moves the coverage report to the pages' folder structure
    - mv htmlcov/ public/coverage/
  artifacts:
    paths:
      - public/
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
