[tox]
envlist =
    py3

[gh-actions]
python =
    3: py3

[testenv]
setenv =
    PYTHONPATH={toxinidir}/tests
    PYTHONUNBUFFERED=yes
passenv =
    *
deps =
    pytest
commands =
    {posargs:pytest -vv --ignore=src}

[testenv:py3]
basepython = {env:TOXPYTHON:python3}
setenv =
    {[testenv]setenv}
usedevelop = true
commands =
    # runs tests on the documentation
    {posargs:pytest --doctest-modules --doctest-ignore-import-errors --cov-report=term-missing --cov=examples/ --cov=src/}
    # runs tests on the installed package and produces an html report specifying the test gaps
    # the report is placed in this folder by default, can be changed by adding ':DEST' after 'html' where DEST is the target folder
    {posargs:pytest --cov-report=term-missing --cov-report=html --cov=mtress}
deps =
    {[testenv]deps}
    pytest-cov
